export const fontImport = `
@import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:wght@600;700&family=Source+Sans+3:wght@400;500;600&family=Caveat:wght@600&display=swap');
`;

export const styles = {
  app: {
    minHeight: "100vh",
    background: "#F6F1E6",
    color: "#2E2A22",
    fontFamily: "'Source Sans 3', sans-serif",
    padding: "22px 18px 32px",
    maxWidth: 480,
    margin: "0 auto",
    boxSizing: "border-box",
  },
  eyebrowRow: { display: "flex", justifyContent: "space-between", alignItems: "baseline" },
  eyebrow: { fontFamily: "'Caveat', cursive", fontSize: 19, color: "#A69C86", marginBottom: -2 },
  backupLinks: { display: "flex", gap: 10 },
  backupBtn: {
    display: "flex",
    alignItems: "center",
    gap: 4,
    background: "none",
    border: "none",
    color: "#7B92B3",
    fontSize: 11.5,
    fontWeight: 600,
    cursor: "pointer",
    padding: 0,
    fontFamily: "'Source Sans 3', sans-serif",
  },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-end", gap: 10 },
  title: { fontFamily: "'Source Serif 4', serif", fontWeight: 700, fontSize: 26, margin: "2px 0 4px", color: "#2E2A22" },
  readout: { display: "flex", gap: 16, paddingBottom: 3 },
  readoutStat: { textAlign: "right" },
  readoutValue: { fontFamily: "'Source Serif 4', serif", fontSize: 19, fontWeight: 700, lineHeight: 1 },
  readoutLabel: { fontSize: 10, color: "#A69C86", marginTop: 2 },
  rule: {
    height: 1,
    margin: "12px 0 16px",
    background: "repeating-linear-gradient(90deg, #D8CFB8 0, #D8CFB8 6px, transparent 6px, transparent 12px)",
  },
  tabs: { display: "flex", gap: 6, marginBottom: 10, flexWrap: "wrap" },
  tab: {
    display: "flex",
    alignItems: "center",
    gap: 5,
    background: "transparent",
    border: "1px solid transparent",
    borderRadius: 20,
    color: "#A69C86",
    fontFamily: "'Source Sans 3', sans-serif",
    fontSize: 12,
    fontWeight: 500,
    padding: "6px 11px",
    cursor: "pointer",
  },
  tabActive: { background: "#FFFDF8", borderWidth: 1, borderStyle: "solid" },
  tabCount: { fontSize: 10.5, color: "#C9BFA8" },
  projectRow: { display: "flex", gap: 6, marginBottom: 16, flexWrap: "wrap" },
  projectChip: {
    background: "transparent",
    border: "1px dashed #D8CFB8",
    borderRadius: 14,
    color: "#A69C86",
    fontSize: 11,
    fontWeight: 500,
    padding: "4px 10px",
    cursor: "pointer",
    fontFamily: "'Source Sans 3', sans-serif",
  },
  projectChipActive: { background: "#EFE7D4", borderStyle: "solid", borderColor: "#D8CFB8", color: "#2E2A22" },
  projectChipCount: { color: "#C9BFA8", marginLeft: 2 },
  projectAddChip: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    background: "transparent",
    border: "1px dashed #C9BFA8",
    borderRadius: 14,
    color: "#8B9D7A",
    fontSize: 11,
    fontWeight: 600,
    padding: "4px 10px",
    cursor: "pointer",
    fontFamily: "'Source Sans 3', sans-serif",
  },
  projectInput: {
    background: "#FFFDF8",
    border: "1px solid #8B9D7A",
    borderRadius: 14,
    color: "#2E2A22",
    fontSize: 11,
    padding: "4px 10px",
    outline: "none",
    fontFamily: "'Source Sans 3', sans-serif",
    minWidth: 120,
  },
  list: { display: "flex", flexDirection: "column", marginBottom: 16 },
  sectionDivider: { display: "flex", alignItems: "baseline", justifyContent: "space-between", padding: "12px 3px 6px" },
  sectionLabel: { fontFamily: "'Caveat', cursive", fontSize: 17, fontWeight: 600 },
  sectionCount: { fontSize: 10.5, color: "#C9BFA8" },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    color: "#A69C86",
    fontSize: 13,
    padding: "28px 4px",
    textAlign: "center",
  },
  swipeWrap: { position: "relative", marginBottom: 9, borderRadius: 8, overflow: "hidden" },
  swipeActionLeft: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 56,
    display: "flex",
    alignItems: "center",
    paddingLeft: 16,
    background: "#DCE5D2",
    color: "#4B5A3E",
  },
  swipeActionRight: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 56,
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingRight: 16,
    background: "#F0D9CE",
    color: "#7A3F2B",
  },
  card: {
    position: "relative",
    display: "flex",
    alignItems: "flex-start",
    gap: 9,
    background: "#FFFDF8",
    border: "1px solid #E5DCC6",
    borderLeft: "4px solid",
    borderRadius: 7,
    padding: "11px 12px",
    boxShadow: "0 1px 2px rgba(59,54,44,0.05)",
    touchAction: "pan-y",
  },
  cardUrgent: { boxShadow: "0 2px 6px rgba(181,101,74,0.18)", borderColor: "#E5DCC6" },
  checkBtn: { background: "none", border: "none", padding: 0, marginTop: 1, cursor: "pointer", lineHeight: 0 },
  cardText: { fontSize: 13.5, lineHeight: 1.42, marginBottom: 5 },
  editInput: {
    width: "100%",
    fontSize: 13.5,
    lineHeight: 1.42,
    marginBottom: 5,
    fontFamily: "'Source Sans 3', sans-serif",
    border: "none",
    borderBottom: "1px dashed #C9BFA8",
    background: "transparent",
    color: "#2E2A22",
    padding: "0 0 2px",
    outline: "none",
  },
  metaRow: { display: "flex", alignItems: "center", gap: 10, flexWrap: "wrap" },
  metaTag: { display: "flex", alignItems: "center", gap: 3, fontSize: 11, color: "#A69C86" },
  projectTag: {
    fontSize: 10.5,
    color: "#7B92B3",
    background: "#EEF1F6",
    borderRadius: 4,
    padding: "1px 6px",
  },
  deadline: { display: "flex", alignItems: "center", gap: 3, fontSize: 11, fontVariantNumeric: "tabular-nums" },
  removeBtn: { background: "none", border: "none", color: "#C9BFA8", cursor: "pointer", padding: 2, lineHeight: 0 },
  addBtn: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    background: "transparent",
    border: "1.5px dashed #D8CFB8",
    color: "#A69C86",
    borderRadius: 8,
    padding: "11px",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    fontFamily: "'Source Sans 3', sans-serif",
  },
  form: {
    background: "#FFFDF8",
    border: "1px solid #E5DCC6",
    borderRadius: 8,
    padding: 12,
    display: "flex",
    flexDirection: "column",
    gap: 8,
    boxShadow: "0 1px 2px rgba(59,54,44,0.05)",
  },
  input: {
    background: "#F6F1E6",
    border: "1px solid #E5DCC6",
    borderRadius: 6,
    color: "#2E2A22",
    padding: "9px 10px",
    fontSize: 13.5,
    fontFamily: "'Source Sans 3', sans-serif",
    outline: "none",
  },
  formRow: { display: "flex", gap: 6, flexWrap: "wrap" },
  select: {
    flex: 1,
    minWidth: 90,
    background: "#F6F1E6",
    border: "1px solid #E5DCC6",
    borderRadius: 6,
    color: "#2E2A22",
    padding: "7px 8px",
    fontSize: 12,
    fontFamily: "'Source Sans 3', sans-serif",
    outline: "none",
  },
  quickDates: { display: "flex", gap: 6, flexWrap: "wrap", alignItems: "center" },
  quickChip: {
    background: "#F6F1E6",
    border: "1px solid #E5DCC6",
    borderRadius: 14,
    color: "#7A7362",
    fontSize: 11,
    padding: "5px 10px",
    cursor: "pointer",
    fontFamily: "'Source Sans 3', sans-serif",
  },
  quickChipActive: { background: "#6E8B99", borderColor: "#6E8B99", color: "#FFFDF8" },
  quickChipDisabled: { opacity: 0.45, cursor: "default" },
  reminderHint: { fontSize: 10.5, color: "#B5654A", width: "100%" },
  reminderRow: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  bellBtn: {
    display: "flex",
    alignItems: "center",
    gap: 3,
    background: "none",
    border: "none",
    color: "#A69C86",
    fontSize: 11,
    cursor: "pointer",
    padding: 0,
    fontFamily: "'Source Sans 3', sans-serif",
  },
  bellBtnActive: { color: "#6E8B99" },
  reminderPopover: {
    marginTop: 8,
    padding: 10,
    background: "#F6F1E6",
    border: "1px solid #E5DCC6",
    borderRadius: 7,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  dateInput: {
    background: "#F6F1E6",
    border: "1px solid #E5DCC6",
    borderRadius: 6,
    color: "#2E2A22",
    padding: "5px 8px",
    fontSize: 11.5,
    fontFamily: "'Source Sans 3', sans-serif",
    outline: "none",
  },
  formActions: { display: "flex", justifyContent: "flex-end", gap: 8, marginTop: 2 },
  cancelBtn: { background: "none", border: "none", color: "#A69C86", fontSize: 12.5, cursor: "pointer", padding: "7px 10px" },
  saveBtn: {
    background: "#8B9D7A",
    border: "none",
    color: "#FFFDF8",
    fontSize: 12.5,
    fontWeight: 600,
    borderRadius: 6,
    padding: "7px 14px",
    cursor: "pointer",
  },
  loading: { display: "flex", justifyContent: "center", padding: 40, color: "#A69C86", fontSize: 13 },
  toast: {
    position: "fixed",
    bottom: 18,
    left: "50%",
    transform: "translateX(-50%)",
    background: "#2E2A22",
    color: "#FFFDF8",
    padding: "9px 16px",
    borderRadius: 8,
    fontSize: 12.5,
    boxShadow: "0 4px 14px rgba(0,0,0,0.2)",
    zIndex: 50,
  },
};
